{% set name = "file" %}
{% set version = "5.46" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: http://ftp.astron.com/pub/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9cc77c7c560c543135edc555af609d5619dbef011997e988ce40a3d75d86088

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - zlib  # [unix]

outputs:
  - name: libmagic
    build:
      run_exports:
        - {{ pin_subpackage('libmagic', max_pin='x') }}
    requirements:
      build:
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - make
      host:
        - zlib  # [unix]
    files:
      - include/magic.h
      - lib/libmagic.*
      - share/misc/magic.mgc
      - lib/pkgconfig/libmagic.pc
    test:
      commands:
        - "test -r $CONDA_PREFIX/lib/libmagic${SHLIB_EXT}"
    about:
      summary: Implementation of the file(1) command
      license: BSD-2-Clause-Darwin
      license_file: COPYING
      dev_url: https://github.com/file/file

  - name: file
    requirements:
      build:
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - make
      host:
        - zlib  # [unix]
      run:
        - {{ pin_subpackage("libmagic", exact=True) }}
    files:
      - bin/file
      - share/man/man*/file*
      - share/man/man*/magic*
      - share/man/man*/libmagic*
    test:
      commands:
        - file -v
        - file --version  # same as above
        - file --help
    about:
      summary: Fine Free File Command
      description: |
        The file command is "a file type guesser", that is, a command-line tool
        that tells you in words what kind of data a file contains. Unlike most GUI
        systems, command-line UNIX systems - with this program leading the charge -
        don't rely on filename extentions to tell you the type of a file, but look
        at the file's actual contents. This is, of course, more reliable, but
        requires a bit of I/O.
      license: BSD-2-Clause-Darwin
      license_file: COPYING
      dev_url: https://github.com/file/file

about:
  home: http://darwinsys.com/file
  summary: Fine Free File Command
  license: BSD-2-Clause-Darwin
  license_file: COPYING
  dev_url: https://github.com/file/file

extra:
  feedstock-name: {{ name|lower }}
  recipe-maintainers:
    - blmaier
    - chrisburr
    - mariusvniekerk
    - mrakitin
